myapps/core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.savesport, name='save_sport_data'),
    path('api/sportnew/', views.savesport_api, name='save_sport_data_api'),
]

rest_fw_insert/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapps.core.urls', namespace='core')),
]

myapps/core/models.py
from django.db import models


# Create your models here.
class Sport(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

myapps/core/forms.py
from django import forms
from .models import Sport

SPORTS_LIST = (
    ('select', '-- SELECT SPORT (Hold Ctrl key to select multiple items) --'),
    ('cricket', 'CRICKET'),
    ('rugby', 'RUGBY'),
    ('tennis', 'TENNIS'),
    ('football', 'FOOTBALL'),
    ('running', 'RUNNING'),
)


class SportInsertForm(forms.ModelForm):
    sportnames = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'readonly': True
        }
    ))

    class Meta:
        model = Sport
        fields = '__all__'
        widgets = {
            'name': forms.SelectMultiple(
                attrs={
                    'class': 'custom-select',
                    'size': 7,
                },
                choices=SPORTS_LIST
            )
        }

myapps/core/views.py
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import Sport
from .serializers import SportSerializer
from .forms import SportInsertForm
import requests


# Create your views here.
@api_view(['POST'])
def savesport_api(request):
    if request.method == 'POST':
        serialized_color_obj = SportSerializer(data=request.data)
        if serialized_color_obj.is_valid():
            serialized_color_obj.save()
            return Response(serialized_color_obj.data, status=status.HTTP_201_CREATED)
        return Response(serialized_color_obj.data, status=status.HTTP_400_BAD_REQUEST)


def savesport(request):
    form = SportInsertForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=False)
            data = {"name": form.cleaned_data.get("sportnames")}
            post_data = requests.post(
                'http://localhost:8000/api/sportnew/',
                headers={'Content-Type': 'application/json'},
                json=data,
            )
            return redirect('/')
    return render(request, 'core/insert.html', {'form': form})

templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="description" content="Application by Aniket Aryamane">
	<meta name="author" content="Aniket Aryamane">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}</title>
	<link rel="apple-touch-icon" href="">

	{% load static %}

	<!-- Link to Bootstrap CSS file -->
	<link rel="stylesheet" href="{% static 'css/vendor/bootstrap/bootstrap.min.css' %}" type="text/css">

	<!-- Link to Materialize CSS file -->
	<!-- <link rel="stylesheet" href="{% static 'css/vendor/materialize/materialize.min.css' %}" type="text/css"> -->

	<!-- Link to Font-Awesome CSS file -->
	<link rel="stylesheet" href="{% static 'css/vendor/font-awesome/css/all.css' %}" type="text/css">

	<!-- Link to your favicon.ico file -->
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

	<!-- Link to your css file -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

</head>

<body>
	{% block content %}{% endblock %}


	<!-- Link to Materialize JS file -->
	<!-- <script src="{% static 'js/vendor/materialize/materialize.min.js' %}"></script> -->

	<!-- JQuery comes first in the list -->
	<script src="{% static 'js/vendor/bootstrap/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap/popper-2.4.0.min.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap/bootstrap.min.js' %}"></script>

	<!-- Link to your js file -->
	<script src="{% static 'js/main.js' %}"></script>

	<!-- Link to your extra javascript/jquery file -->
	{% block extra_js %}{% endblock %}
</body>

</html>

templates/core/insert.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create & Consume REST Framework to Insert Records via Select Dropdown{% endblock %}

{% block content %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-10">
				<h1>Insert Data</h1>
				<hr>
				<form method="post" novalidate>
					{% csrf_token %}
					{{ form|crispy }}
					<button type="submit" class="btn btn-outline-secondary my-3">Insert Record</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block extra_js %}
	<script>
		$("select option:first").attr("disabled", "true");
		$('#id_name').on('change', function() {
			$('#id_sportnames').val($(this).val());
		});
	</script>
{% endblock %}